### ISSUE TITLE
Beta 4.0.0 Unexpected Position: Invalid Bestiary Section

### ISSUE THREAD

**Issue by Malitahj** [TEdit/Terraria-Map-Editor#1194]
## What were you doing when the issue occured?
Launched the app in administrator mode
Attempted to open my play-through map
Was given this error.
## Can you reproduce the issue?
Simply by trying to load this world. Creating a new journey world and loading it works perfectly fine. It's just this one.
## What version of Terraria are you using?
1.4.0.2
## Post relevant contents of log or attach log file _**(very important)**_:
TEdit v4.0.20139.1401
TEdit Max World: 226 Current World: 226
The error is: Unexpected Position: Invalid Bestiary Section
System.IO.FileFormatException: Unexpected Position: Invalid Bestiary Section at TEditXNA.Terraria.World.LoadV2(BinaryReader b; String filename, World w) in C:\dev\home\code\Terraria\Terraria-Map-Editro\TEditXna\Terraria\World.FileV2.cs:line 742 at TEditXNA.Terraria.World.LoadWorld(String filename) in C:\dev\home\code\Terraria\Terraria-Map-Editor\TEditXna\Terraria\World.cs:line 124

**Comment by jerry123z** [comment]
looks to be a duplicate of #1192.

**Comment by SuperKael** [comment]
I don't think so. Mine was an EndOfStreamException, while this one is a FileFormatException.

**Comment by BinaryConstruct** [comment]
Should be fixed with 35501ce2615543bd7c53101bb46c8ecb9699af25

**Comment by Malitahj** [comment]
Still getting the same error. Do I have to wait for the next beta release to see a change?
